"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const dotenv_1 = __importDefault(require("dotenv"));
const mongoConfig_1 = __importDefault(require("./db/mongo/mongoConfig"));
const authRoutes_1 = __importDefault(require("./routes/authRoutes"));
const errorHandler_1 = require("./middlewares/errorHandler");
(0, mongoConfig_1.default)();
const app = (0, express_1.default)();
dotenv_1.default.config({ path: "./.env" });
const port = parseInt(process.env.PORT);
app.use(express_1.default.json());
app.use(express_1.default.urlencoded({ extended: true }));
app.use("/auth/", authRoutes_1.default);
app.use(errorHandler_1.notFound);
app.use(errorHandler_1.errorHandle);
app.listen(port, () => console.log("Server up and running at port", port));
